{"uuid": "7ab8d0fa-f6e3-4311-a0bd-bbaff5bfefa0", "children": ["637355d6-68e6-4b4d-9d75-896c8445f15c"], "befores": [{"name": "setup_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114\nCurrent browser version is 117.0.5938.92 with binary path C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x008FA813+48355]\n\t(No symbol) [0x0088C4B1]\n\t(No symbol) [0x00795358]\n\t(No symbol) [0x007B61AC]\n\t(No symbol) [0x007B1EF3]\n\t(No symbol) [0x007B0579]\n\t(No symbol) [0x007E0C55]\n\t(No symbol) [0x007E093C]\n\t(No symbol) [0x007DA536]\n\t(No symbol) [0x007B82DC]\n\t(No symbol) [0x007B93DD]\n\tGetHandleVerifier [0x00B5AABD+2539405]\n\tGetHandleVerifier [0x00B9A78F+2800735]\n\tGetHandleVerifier [0x00B9456C+2775612]\n\tGetHandleVerifier [0x009851E0+616112]\n\t(No symbol) [0x00895F8C]\n\t(No symbol) [0x00892328]\n\t(No symbol) [0x0089240B]\n\t(No symbol) [0x00884FF7]\n\tBaseThreadInitThunk [0x76A36B89+25]\n\tRtlGetFullPathName_UEx [0x77678F9F+1215]\n\tRtlGetFullPathName_UEx [0x77678F6D+1165]\n\n", "trace": "  File \"c:\\users\\sf314-510g\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\sf314-510g\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\sf314-510g\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\SF314-510G\\Desktop\\theout\\selenium-pytest-python-nonBDD\\DemoQABookStore\\testcases\\ui\\conftest.py\", line 22, in setup_driver\n    DriverManager.init_driver(pytest.driver_conf)\n  File \"C:\\Users\\SF314-510G\\Desktop\\theout\\selenium-pytest-python-nonBDD\\DemoQABookStore\\core\\driver\\driver_manager.py\", line 16, in init_driver\n    cls.driver = driver_mapping[config.driver].create_driver(config)\n  File \"C:\\Users\\SF314-510G\\Desktop\\theout\\selenium-pytest-python-nonBDD\\DemoQABookStore\\core\\driver\\driver_types\\chrome_driver.py\", line 16, in create_driver\n    self._driver = webdriver.Chrome(service=Service(), options=options)\n  File \"c:\\users\\sf314-510g\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 49, in __init__\n    super().__init__(\n  File \"c:\\users\\sf314-510g\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 54, in __init__\n    super().__init__(\n  File \"c:\\users\\sf314-510g\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 206, in __init__\n    self.start_session(capabilities)\n  File \"c:\\users\\sf314-510g\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 291, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"c:\\users\\sf314-510g\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\sf314-510g\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1695664681923, "stop": 1695664689198}], "start": 1695664681923, "stop": 1695664689325}